en:
  languageName: English
  weight: 1
  ### copyright (markdown can be used) ###
  copyright: "Copyright &copy; {{< current_year >}} Company Name. All Rights Reserved. [Dot Org Theme](https://github.com/cncf/dot-org-hugo-theme) for Hugo by [CNCF](https://www.cncf.io)."
  title: "EVERSE"
  description: "Site Description"
  params:
    ### accessibility ###
    # accessibility:
    #   skip_text: "Skip to content"
    #   help_text: "Accessibility Statement"
    #   help_url: "/example-page/"
    ### calls to action ###
    main_cta:
      text: "Join"
      link: "/how-to-join/"
    footer_cta:
      text: "How to join"
      link: "/how-to-join/"
    # github_edit: "Edit this page on GitHub"
  ### example menu showing children ###
  menu:
    main:
      ### About ### 
    - identifier: "about"
      name: "About"
      url: "/example-page/"
      weight: 1
    - identifier: "about-1"
      name: "Objectives"
      url: "/objectives/"
      weight: 1
      post: "Lorem ipsum dolor sit amet consectetuer adipiscing elit aenean commodo."
      parent: "about"
    - identifier: "about-2"
      name: "Consortium"
      url: "/consortium/"
      weight: 2
      post: "Aenean commodo ligula get dolor. Aenean massa."
      parent: "about"
    - identifier: "about-3"
      name: "Work Packages"
      url: "/work-packages/"
      weight: 3
      post: "Nulla consequat massa quis enim. Donec pede justo."
      parent: "about"

      ### Services ###
    - identifier: "services"
      name: "Services"
      url: "/example-page/"
      weight: 2
    - identifier: "services-1"
      name: "RSQkit"
      url: "/rsqkit/"
      weight: 1
      post: "Lorem ipsum dolor sit amet consectetuer adipiscing elit aenean commodo."
      parent: "services"
    - identifier: "services-2"
      name: "SMP"
      url: "/smp/"
      weight: 2
      post: "Nulla consequat massa quis enim. Donec pede justo."
      parent: "services"

      ### Training & Recognision ###
    - identifier: "training"
      name: "Training"
      url: "/example-page/"
      weight: 3
    - identifier: "training-1"
      name: "Training Material"
      url: "/training-material/"
      weight: 1
      post: "Lorem ipsum dolor sit amet consectetuer adipiscing elit aenean commodo."
      parent: "training"
    - identifier: "training-2"
      name: "Training Events"
      url: "/training-events/"
      weight: 2
      post: "Nulla consequat massa quis enim. Donec pede justo."
      parent: "training"
    - identifier: "training-3"
      name: "Recognition Framework"
      url: "/recognition-framework/"
      weight: 3
      post: "Aenean commodo ligula get dolor. Aenean massa. "
      parent: "training"

      ### Resources ###
    - identifier: "resources"
      name: "Resources"
      url: "/example-page/"
      weight: 4
    - identifier: "resources-1"
      name: "Deliverables and Milestones"
      url: "/deliverables-and-milestones/"
      weight: 1
      post: "Lorem ipsum dolor sit amet consectetuer adipiscing elit aenean commodo."
      parent: "resources"
    - identifier: "resources-2"
      name: "Presentations"
      url: "/presentations/"
      weight: 2
      post: "Nulla consequat massa quis enim. Donec pede justo."
      parent: "resources"
    - identifier: "resources-3"
      name: "Videos"
      url: "/videos/"
      weight: 3
      post: "Aenean commodo ligula get dolor. Aenean massa. "
      parent: "resources"
    - identifier: "resources-4"
      name: "Visual Identity"
      url: "/visual-identity/"
      weight: 4
      post: "Aenean commodo ligula get dolor. Aenean massa. "
      parent: "resources"
    - identifier: "resources-5"
      name: "Artwork"
      url: "/artwork/"
      weight: 5
      post: "Aenean commodo ligula get dolor. Aenean massa. "
      parent: "resources"
    - identifier: "resources-6"
      name: "Zotero and Zenodo"
      url: "/zotero-and-zenodo/"
      weight: 6
      post: "Aenean commodo ligula get dolor. Aenean massa. "
      parent: "resources"

      ### Network ###
    - identifier: "network"
      name: "Network"
      url: "/example-page/"
      weight: 5
    - identifier: "network-1"
      name: "Communities"
      url: "/communities/"
      weight: 1
      post: "Lorem ipsum dolor sit amet consectetuer adipiscing elit aenean commodo."
      parent: "network"
    - identifier: "network-2"
      name: "Competence Centres"
      url: "/competence-centres/"
      weight: 2
      post: "Nulla consequat massa quis enim. Donec pede justo."
      parent: "network"

      ### Demo Page ###
    # - identifier: "demo-page"
    #   name: "Demo Page"
    #   url: "/demo-page/"
    #   weight: 3
    # - identifier: "faq"
    #   name: "FAQs"
    #   url: "/faq/"
    #   weight: 4
    # - identifier: "blog"
    #   name: "Blog"
    #   url: "/blog/"
    #   weight: 5
# es:
#   languageName: Spanish
#   contentDir: content/es
#   weight: 2
#   title: "Título del Sitio"
#   description: "Descripción del Sitio"
#   menu:
#     main:
#     - identifier: "about"
#       name: "Acerca de"
#       url: "/example-page/"
#       weight: 1
#     - identifier: "child-1"
#       name: "Página Hija de Ejemplo"
#       url: "/example-page/"
#       weight: 1
#       parent: "about"
#     - identifier: "faq"
#       name: "FAQs"
#       url: "/faq/"
#       weight: 3
#     - identifier: "blog"
#       name: "Blog"
#       url: "/blog/"
#       weight: 2
